# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            tonylee 
tagline:          Seasoned webDevOps
description:      "hmmm"
url:              aiegoo.github.io
baseurl:          /blackdocu
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           tonylee
  url:            https://github.com/aiegoo

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc
