---
title: tonylee
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
tagline: Seasoned webDevOps
description: `1050446037`
url: aiegoo.github.io
baseurl: "/blackdocu/"
author:
  name: tonylee
  url: https://github.com/aiegoo
paginate: 1
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
version: 2.0.1
github:
  repo: https://github.com/karloespiritu/blackdoc
